databases:
  - name: db
    databaseName: chordbook
    user: chordbook

services:
  - type: web
    name: app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: /ping
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: APP_API_URL
        value: /
      - key: GOOD_JOB_EXECUTION_MODE
        value: async
      - key: GOOD_JOB_MAX_THREADS
        value: 1
      - key: NODE_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: THEAUDIODB_API_KEY
        sync: false
  - type: pserv
    name: elasticsearch
    env: docker
    dockerfilePath: ./elasticsearch/Dockerfile
    dockerContext: ./elasticsearch
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 10
    autoDeploy: false
    envVars:
    - key: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    - key: discovery.type
      value: single-node
    - key: cluster.name
      value: elastic
