databases:
  - name: chordbook
    databaseName: chordbook
    user: chordbook

services:
  - type: web
    name: chordbook
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chordbook
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        generateValue: true
      - key: APP_API_URL
        value: /
      - key: GOOD_JOB_EXECUTION_MODE
        value: async
      - key: GOOD_JOB_MAX_THREADS
        value: 1
      - key: NODE_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: THEAUDIODB_API_KEY
        sync: false
