name: Lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eslint:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
      - name: Run yarn lint
        run: |
          yarn install
          yarn lint
